// One song per string; you can add/remove later.
window.SONGS = [
  "Don't Stop Me Now",
  "Poker Face",
  "Rosas",
  "The Final Countdown",
  "Macarena",
  "Ave María",
  "Baila el Chiki Chiki",
  "Zapatillas",
  "Princesas",
  "Física o Química",
  "Marta, Sebas, Guille y los demás",
  "Waka Waka",
  "Thriller",
  "Mari Carmen",
  "Mala Mujer",
  "Caminando por la Vida",
  "Dragostea din tei",
  "Bizcochito",
  "Back in Black",
  "The Best of Both Worlds",
  "This Is Me",
  "Dancing Queen",
  "Zombie",
  "What makes you beautiful",
  "Let me love you",
  "Fiebre",
  "Toxic",
  "All I Want for Christmas is you",
  "Candy",
  "All Star",
  "Como una Ola"
];
